server:
  port: 8080

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/studyhub?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: studyhub
    password: secret

  jpa:
    hibernate:
      ddl-auto: update    # 개발 중 자동 테이블 생성
    properties:
      hibernate:
        format_sql: true